### ISSUE TITLE
Transfer this repo to @TheTorProject github account

### ISSUE THREAD

**Issue by hellais** [lindanlee/tor-media#1]
I find this repo super useful!

It would be great if we could move it to the official @TheTorProject github org.

**Comment by lindanlee** [comment]
I think it would be useful as well! Do you know the process of doing such a thing?

**Comment by hellais** [comment]
> I think it would be useful as well! Do you know the process of doing such a thing?

You need to go to the settings page of the repository and do "Transfer ownership" of the repository. I create the UX team on @TheTorProject and invited you there (https://github.com/orgs/TheTorProject/teams/ux, go here to accept it https://github.com/TheTorProject).

When the repo is transferred I will setup the appropriate ACL on the team so that you have admin access on the repo(s).

**Comment by lindanlee** [comment]
I just tried to transfer the ownership of the repository to @TheTorProject, but I don't have the correct permissions ("You don’t have the permission to create repositories on TheTorProject"). 

Could you give me the appropriate permissions, if you have that ability?

**Comment by hellais** [comment]
> Could you give me the appropriate permissions, if you have that ability?

Try now.

**Comment by lindanlee** [comment]
Whoo!

**Comment by lindanlee** [comment]
I still don't have admin privileges though. :(

**Comment by hellais** [comment]
> I still don't have admin privileges though. :(

yup, now that the repo is transferred I can set those up.

**Comment by hellais** [comment]
Ok, now you and everybody else on the UX team has admin rights to every repo part of the UX team.

**Comment by lindanlee** [comment]
Eek, I still can't send invitations to anyone for my team because I'm not the owner. Can I be a co-owner?

**Comment by hellais** [comment]
> Eek, I still can't send invitations to anyone for my team because I'm not the owner. Can I be a co-owner?

I did put you as "Team maintainer", which is the highest thing the UI seems to allow me to do, it claims that this should allow you to add members.

![screen shot 2017-02-14 at 16 39 36 0000](https://cloud.githubusercontent.com/assets/424620/22938649/494a8758-f2d4-11e6-9e71-ac881c2601b5.png)

What error are you seeing when adding members?

**Comment by hellais** [comment]
I think the "Owner" next to my name means I am the "Owner" of @TheTorProject and not the owner of that team.

**Comment by lindanlee** [comment]
![image](https://cloud.githubusercontent.com/assets/6580269/22939268/bf555008-f2a3-11e6-8bb5-50ad3cdbe3fd.png)

This is the error.

**Comment by hellais** [comment]
Ah I see the problem. I believe you can only add members to the team if they are already part of the organisation. Can you give me a list of the handles you would like to invite to @TheTorProject and will invite them?

**Comment by hellais** [comment]
I think you can add anybody as an "External collaborator" though, that is done from the settings of the repo.

**Comment by lindanlee** [comment]
Hmm,.. I think that the second invite still says "only organization owners can send invitations."

**Comment by lindanlee** [comment]
I'll try the external collaborator thing? But I don't know how that works.

**Comment by hellais** [comment]
Yeah the thing is that to invite somebody to join the organisation (@thetorproject) you need to have admin rights on the whole organisation. Once the person is in the organisation, though, also team coordinators can add them to the team.

**Comment by lindanlee** [comment]
Ah, I see.
